[book]
title = "$PROJECT_NAME"
language = "en"

[build]
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
no-section-label = true
# google-analytics = "123456"
git-repository-url = "https://github.com/$ORG/$REPO"
git-repository-icon = "fa-github"
