[book]
title = "PeerVault Architecture & RFCs Book"
language = "en"

[build]
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
no-section-label = true
google-analytics = "UA-52121593-5"
git-repository-url = "https://github.com/PeerVault/architecture-rfcs"
git-repository-icon = "fa-github"
additional-css = ["mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]